/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../../routes/__root'
import { Route as WelcomeRouteImport } from './../../routes/welcome'
import { Route as cardfolioIndexRouteImport } from './../../routes/(cardfolio)/index'
import { Route as cardfolioAnimesRouteImport } from './../../routes/(cardfolio)/animes'
import { Route as cardfolioBlankRouteImport } from './../../routes/(cardfolio)/blank'
import { Route as cardfolioBookmarksRouteImport } from './../../routes/(cardfolio)/bookmarks'
import { Route as cardfolioColophonRouteImport } from './../../routes/(cardfolio)/colophon'
import { Route as cardfolioInterestsRouteImport } from './../../routes/(cardfolio)/interests'
import { Route as cardfolioLanguagesRouteImport } from './../../routes/(cardfolio)/languages'
import { Route as cardfolioNopeRouteImport } from './../../routes/(cardfolio)/nope'
import { Route as cardfolioQuestionsRouteImport } from './../../routes/(cardfolio)/questions'
import { Route as cardfolioSlashesRouteImport } from './../../routes/(cardfolio)/slashes'
import { Route as cardfolioYepRouteImport } from './../../routes/(cardfolio)/yep'
import { Route as AppsIndexRouteImport } from './../../routes/apps/index'
import { Route as AppsSettingsRouteImport } from './../../routes/apps/settings'
import { Route as AppsSucofRouteImport } from './../../routes/apps/sucof'
import { Route as AppsWritingAreaRouteImport } from './../../routes/apps/writing-area'
import { Route as AppslyricsStudioLyricsEditorRouteImport } from './../../routes/apps/(lyrics-studio)/lyrics-editor'
import { Route as AppslyricsStudioLyricsPlayerRouteImport } from './../../routes/apps/(lyrics-studio)/lyrics-player'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const cardfolioIndexRoute = cardfolioIndexRouteImport.update({
  id: '/(cardfolio)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const cardfolioAnimesRoute = cardfolioAnimesRouteImport.update({
  id: '/(cardfolio)/animes',
  path: '/animes',
  getParentRoute: () => rootRouteImport,
} as any)
const cardfolioBlankRoute = cardfolioBlankRouteImport.update({
  id: '/(cardfolio)/blank',
  path: '/blank',
  getParentRoute: () => rootRouteImport,
} as any)
const cardfolioBookmarksRoute = cardfolioBookmarksRouteImport.update({
  id: '/(cardfolio)/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const cardfolioColophonRoute = cardfolioColophonRouteImport.update({
  id: '/(cardfolio)/colophon',
  path: '/colophon',
  getParentRoute: () => rootRouteImport,
} as any)
const cardfolioInterestsRoute = cardfolioInterestsRouteImport.update({
  id: '/(cardfolio)/interests',
  path: '/interests',
  getParentRoute: () => rootRouteImport,
} as any)
const cardfolioLanguagesRoute = cardfolioLanguagesRouteImport.update({
  id: '/(cardfolio)/languages',
  path: '/languages',
  getParentRoute: () => rootRouteImport,
} as any)
const cardfolioNopeRoute = cardfolioNopeRouteImport.update({
  id: '/(cardfolio)/nope',
  path: '/nope',
  getParentRoute: () => rootRouteImport,
} as any)
const cardfolioQuestionsRoute = cardfolioQuestionsRouteImport.update({
  id: '/(cardfolio)/questions',
  path: '/questions',
  getParentRoute: () => rootRouteImport,
} as any)
const cardfolioSlashesRoute = cardfolioSlashesRouteImport.update({
  id: '/(cardfolio)/slashes',
  path: '/slashes',
  getParentRoute: () => rootRouteImport,
} as any)
const cardfolioYepRoute = cardfolioYepRouteImport.update({
  id: '/(cardfolio)/yep',
  path: '/yep',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsIndexRoute = AppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsSettingsRoute = AppsSettingsRouteImport.update({
  id: '/apps/settings',
  path: '/apps/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsSucofRoute = AppsSucofRouteImport.update({
  id: '/apps/sucof',
  path: '/apps/sucof',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsWritingAreaRoute = AppsWritingAreaRouteImport.update({
  id: '/apps/writing-area',
  path: '/apps/writing-area',
  getParentRoute: () => rootRouteImport,
} as any)
const AppslyricsStudioLyricsEditorRoute =
  AppslyricsStudioLyricsEditorRouteImport.update({
    id: '/apps/(lyrics-studio)/lyrics-editor',
    path: '/apps/lyrics-editor',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppslyricsStudioLyricsPlayerRoute =
  AppslyricsStudioLyricsPlayerRouteImport.update({
    id: '/apps/(lyrics-studio)/lyrics-player',
    path: '/apps/lyrics-player',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/welcome': typeof WelcomeRoute
  '/animes': typeof cardfolioAnimesRoute
  '/blank': typeof cardfolioBlankRoute
  '/bookmarks': typeof cardfolioBookmarksRoute
  '/colophon': typeof cardfolioColophonRoute
  '/interests': typeof cardfolioInterestsRoute
  '/languages': typeof cardfolioLanguagesRoute
  '/nope': typeof cardfolioNopeRoute
  '/questions': typeof cardfolioQuestionsRoute
  '/slashes': typeof cardfolioSlashesRoute
  '/yep': typeof cardfolioYepRoute
  '/apps/settings': typeof AppsSettingsRoute
  '/apps/sucof': typeof AppsSucofRoute
  '/apps/writing-area': typeof AppsWritingAreaRoute
  '/': typeof cardfolioIndexRoute
  '/apps/': typeof AppsIndexRoute
  '/apps/lyrics-editor': typeof AppslyricsStudioLyricsEditorRoute
  '/apps/lyrics-player': typeof AppslyricsStudioLyricsPlayerRoute
}
export interface FileRoutesByTo {
  '/welcome': typeof WelcomeRoute
  '/animes': typeof cardfolioAnimesRoute
  '/blank': typeof cardfolioBlankRoute
  '/bookmarks': typeof cardfolioBookmarksRoute
  '/colophon': typeof cardfolioColophonRoute
  '/interests': typeof cardfolioInterestsRoute
  '/languages': typeof cardfolioLanguagesRoute
  '/nope': typeof cardfolioNopeRoute
  '/questions': typeof cardfolioQuestionsRoute
  '/slashes': typeof cardfolioSlashesRoute
  '/yep': typeof cardfolioYepRoute
  '/apps/settings': typeof AppsSettingsRoute
  '/apps/sucof': typeof AppsSucofRoute
  '/apps/writing-area': typeof AppsWritingAreaRoute
  '/': typeof cardfolioIndexRoute
  '/apps': typeof AppsIndexRoute
  '/apps/lyrics-editor': typeof AppslyricsStudioLyricsEditorRoute
  '/apps/lyrics-player': typeof AppslyricsStudioLyricsPlayerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/welcome': typeof WelcomeRoute
  '/(cardfolio)/animes': typeof cardfolioAnimesRoute
  '/(cardfolio)/blank': typeof cardfolioBlankRoute
  '/(cardfolio)/bookmarks': typeof cardfolioBookmarksRoute
  '/(cardfolio)/colophon': typeof cardfolioColophonRoute
  '/(cardfolio)/interests': typeof cardfolioInterestsRoute
  '/(cardfolio)/languages': typeof cardfolioLanguagesRoute
  '/(cardfolio)/nope': typeof cardfolioNopeRoute
  '/(cardfolio)/questions': typeof cardfolioQuestionsRoute
  '/(cardfolio)/slashes': typeof cardfolioSlashesRoute
  '/(cardfolio)/yep': typeof cardfolioYepRoute
  '/apps/settings': typeof AppsSettingsRoute
  '/apps/sucof': typeof AppsSucofRoute
  '/apps/writing-area': typeof AppsWritingAreaRoute
  '/(cardfolio)/': typeof cardfolioIndexRoute
  '/apps/': typeof AppsIndexRoute
  '/apps/(lyrics-studio)/lyrics-editor': typeof AppslyricsStudioLyricsEditorRoute
  '/apps/(lyrics-studio)/lyrics-player': typeof AppslyricsStudioLyricsPlayerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/welcome'
    | '/animes'
    | '/blank'
    | '/bookmarks'
    | '/colophon'
    | '/interests'
    | '/languages'
    | '/nope'
    | '/questions'
    | '/slashes'
    | '/yep'
    | '/apps/settings'
    | '/apps/sucof'
    | '/apps/writing-area'
    | '/'
    | '/apps/'
    | '/apps/lyrics-editor'
    | '/apps/lyrics-player'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/welcome'
    | '/animes'
    | '/blank'
    | '/bookmarks'
    | '/colophon'
    | '/interests'
    | '/languages'
    | '/nope'
    | '/questions'
    | '/slashes'
    | '/yep'
    | '/apps/settings'
    | '/apps/sucof'
    | '/apps/writing-area'
    | '/'
    | '/apps'
    | '/apps/lyrics-editor'
    | '/apps/lyrics-player'
  id:
    | '__root__'
    | '/welcome'
    | '/(cardfolio)/animes'
    | '/(cardfolio)/blank'
    | '/(cardfolio)/bookmarks'
    | '/(cardfolio)/colophon'
    | '/(cardfolio)/interests'
    | '/(cardfolio)/languages'
    | '/(cardfolio)/nope'
    | '/(cardfolio)/questions'
    | '/(cardfolio)/slashes'
    | '/(cardfolio)/yep'
    | '/apps/settings'
    | '/apps/sucof'
    | '/apps/writing-area'
    | '/(cardfolio)/'
    | '/apps/'
    | '/apps/(lyrics-studio)/lyrics-editor'
    | '/apps/(lyrics-studio)/lyrics-player'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  WelcomeRoute: typeof WelcomeRoute
  cardfolioAnimesRoute: typeof cardfolioAnimesRoute
  cardfolioBlankRoute: typeof cardfolioBlankRoute
  cardfolioBookmarksRoute: typeof cardfolioBookmarksRoute
  cardfolioColophonRoute: typeof cardfolioColophonRoute
  cardfolioInterestsRoute: typeof cardfolioInterestsRoute
  cardfolioLanguagesRoute: typeof cardfolioLanguagesRoute
  cardfolioNopeRoute: typeof cardfolioNopeRoute
  cardfolioQuestionsRoute: typeof cardfolioQuestionsRoute
  cardfolioSlashesRoute: typeof cardfolioSlashesRoute
  cardfolioYepRoute: typeof cardfolioYepRoute
  AppsSettingsRoute: typeof AppsSettingsRoute
  AppsSucofRoute: typeof AppsSucofRoute
  AppsWritingAreaRoute: typeof AppsWritingAreaRoute
  cardfolioIndexRoute: typeof cardfolioIndexRoute
  AppsIndexRoute: typeof AppsIndexRoute
  AppslyricsStudioLyricsEditorRoute: typeof AppslyricsStudioLyricsEditorRoute
  AppslyricsStudioLyricsPlayerRoute: typeof AppslyricsStudioLyricsPlayerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(cardfolio)/': {
      id: '/(cardfolio)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof cardfolioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(cardfolio)/animes': {
      id: '/(cardfolio)/animes'
      path: '/animes'
      fullPath: '/animes'
      preLoaderRoute: typeof cardfolioAnimesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(cardfolio)/blank': {
      id: '/(cardfolio)/blank'
      path: '/blank'
      fullPath: '/blank'
      preLoaderRoute: typeof cardfolioBlankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(cardfolio)/bookmarks': {
      id: '/(cardfolio)/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof cardfolioBookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(cardfolio)/colophon': {
      id: '/(cardfolio)/colophon'
      path: '/colophon'
      fullPath: '/colophon'
      preLoaderRoute: typeof cardfolioColophonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(cardfolio)/interests': {
      id: '/(cardfolio)/interests'
      path: '/interests'
      fullPath: '/interests'
      preLoaderRoute: typeof cardfolioInterestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(cardfolio)/languages': {
      id: '/(cardfolio)/languages'
      path: '/languages'
      fullPath: '/languages'
      preLoaderRoute: typeof cardfolioLanguagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(cardfolio)/nope': {
      id: '/(cardfolio)/nope'
      path: '/nope'
      fullPath: '/nope'
      preLoaderRoute: typeof cardfolioNopeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(cardfolio)/questions': {
      id: '/(cardfolio)/questions'
      path: '/questions'
      fullPath: '/questions'
      preLoaderRoute: typeof cardfolioQuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(cardfolio)/slashes': {
      id: '/(cardfolio)/slashes'
      path: '/slashes'
      fullPath: '/slashes'
      preLoaderRoute: typeof cardfolioSlashesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(cardfolio)/yep': {
      id: '/(cardfolio)/yep'
      path: '/yep'
      fullPath: '/yep'
      preLoaderRoute: typeof cardfolioYepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/': {
      id: '/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof AppsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/settings': {
      id: '/apps/settings'
      path: '/apps/settings'
      fullPath: '/apps/settings'
      preLoaderRoute: typeof AppsSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/sucof': {
      id: '/apps/sucof'
      path: '/apps/sucof'
      fullPath: '/apps/sucof'
      preLoaderRoute: typeof AppsSucofRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/writing-area': {
      id: '/apps/writing-area'
      path: '/apps/writing-area'
      fullPath: '/apps/writing-area'
      preLoaderRoute: typeof AppsWritingAreaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/(lyrics-studio)/lyrics-editor': {
      id: '/apps/(lyrics-studio)/lyrics-editor'
      path: '/apps/lyrics-editor'
      fullPath: '/apps/lyrics-editor'
      preLoaderRoute: typeof AppslyricsStudioLyricsEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/(lyrics-studio)/lyrics-player': {
      id: '/apps/(lyrics-studio)/lyrics-player'
      path: '/apps/lyrics-player'
      fullPath: '/apps/lyrics-player'
      preLoaderRoute: typeof AppslyricsStudioLyricsPlayerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  WelcomeRoute: WelcomeRoute,
  cardfolioAnimesRoute: cardfolioAnimesRoute,
  cardfolioBlankRoute: cardfolioBlankRoute,
  cardfolioBookmarksRoute: cardfolioBookmarksRoute,
  cardfolioColophonRoute: cardfolioColophonRoute,
  cardfolioInterestsRoute: cardfolioInterestsRoute,
  cardfolioLanguagesRoute: cardfolioLanguagesRoute,
  cardfolioNopeRoute: cardfolioNopeRoute,
  cardfolioQuestionsRoute: cardfolioQuestionsRoute,
  cardfolioSlashesRoute: cardfolioSlashesRoute,
  cardfolioYepRoute: cardfolioYepRoute,
  AppsSettingsRoute: AppsSettingsRoute,
  AppsSucofRoute: AppsSucofRoute,
  AppsWritingAreaRoute: AppsWritingAreaRoute,
  cardfolioIndexRoute: cardfolioIndexRoute,
  AppsIndexRoute: AppsIndexRoute,
  AppslyricsStudioLyricsEditorRoute: AppslyricsStudioLyricsEditorRoute,
  AppslyricsStudioLyricsPlayerRoute: AppslyricsStudioLyricsPlayerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
