# https://taskfile.dev
version: '3'

dotenv: ['.env']

vars:
  OPENAPI_SPEC_URL: http://localhost:5200/openapi.yml
  OPENAPI_OUTPUT_FILE: ./src/features/api/openapi.yml

tasks:
  default: task --list-all

  dev:
    aliases: [d]
    cmds:
      - vp dev --host --open

  preview: vp preview --host

  install: vp install

  setup:
    cmds:
      - task: install
      - task: i18n

  build: vp build

  repo:nuke:
    cmds:
      - rm -rf node_modules/
      - rm -rf .tanstack/
      - rm -rf dist/

  publish:
    cmds:
      - task: typecheck
      - task: build

  typecheck:
    aliases: [t]
    cmds:
      - vpr tsc -b

  format:
    aliases: [f]
    cmds:
      - vp fmt . --write

  api:download:
    aliases: [api]
    desc: Download OpenAPI definition
    cmds:
      - curl --ssl-no-revoke -o "{{.OPENAPI_OUTPUT_FILE}}" "{{.OPENAPI_SPEC_URL}}"

  i18n:
    cmds:
      - vpr typesafe-i18n --no-watch

  i18n:watch:
    aliases: [iw]
    cmds:
      - vpr typesafe-i18n

  lint:
    aliases: [l]
    cmds:
      - vp lint

  lint:fix:
    aliases: [lf]
    cmds:
      - vp lint --fix

  check:
    aliases: [c]
    cmds:
      - vp check

  check:fix:
    aliases: [cf]
    cmds:
      - vp check --fix

  test: vp test

  test:watch: vp test --watch

  deploy:
    desc: Deploy app with chabokan
    cmds:
      - cd dist/ && bun run chabok -- deploy
